### PR TITLE
Gwordle Beasts

### PR DESCRIPTION
**Pull request by bezzdev**
Hi there!

I've made a Grotto Beasts themed wordle game at [https://gwordlebeasts.com/](https://gwordlebeasts.com/)
I would really appreciate it if I could add this to the list of Jerma sites.

If you think this sits outside the scope of the list then that's totally fine!

Thanks!
- bezz

### CODE REVIEW

**Comment by bezzdev** [comment]
You can find me on discord/twitter @bezzdev if you have any questions. 
Thanks again

**Comment by s-crypt** [comment]
In order to add this project to jerma.io, it would need to be open source, and preferably then we could add it to the org.

**Comment by bezzdev** [comment]
Hi, the code is publicly available here: [https://github.com/bezzdev/gwordle_beasts](https://github.com/bezzdev/gwordle_beasts)

**Comment by s-crypt** [comment]
Added to the homepage! Would you want to move it under the jerma.io domain on something like gwordle.jerma.io so you dont have to pay for the domain?

**Comment by bezzdev** [comment]
Awesome, thanks for adding it. 
I will keep the current domain for now, if that ever changes I'll let you know.
How are updates usually deployed for this project?

**Comment by s-crypt** [comment]
They are deployed via cloudlfare pages. There was a deployment error so we are trying to figure that out. Usually it deploys within a minute.

**Comment by s-crypt** [comment]
@stabswell did some work to fix the site and now gwordlebeasts is on the homepage!

**Comment by bezzdev** [comment]
Perfect!
Thanks for getting it all sorted.

**Comment by bezzdev** [comment]
I'm looking the the site just now, looks like the link description doesn't match what I sent over.
Any idea why this was changed?

**Comment by s-crypt** [comment]
Oh I didnt merge the commit, I just manually added it to the site and added (what I think is) a fitting but fun description

**Comment by s-crypt** [comment]
@bezzdev would you like to join the org, move the repo to JermaSites, and use gwordlebeasts.jerma.io?

**Pull request closed without merging**
